<a href="https://colab.research.google.com/github/cristiangromero/LGRT-PIA/blob/main/IAhora_Parte1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

vocabulario = [
    'perro', 'gato', 'elefante', 'casa',
    'coche', 'avión', 'bicicleta', 'león'
]

# Crear representación One-Hot
one_hot = np.eye(len(vocabulario))

print("Representaciones One-Hot:")
for palabra, vector in zip(vocabulario, one_hot):
    print(f"{palabra}: {vector.astype(int)}")

# Calcular matriz de similitud coseno
matriz_similitud = cosine_similarity(one_hot)

print("\nMatriz de similitud:")
print(np.round(matriz_similitud, 2))

Representaciones One-Hot:
perro: [1 0 0 0 0 0 0 0]
gato: [0 1 0 0 0 0 0 0]
elefante: [0 0 1 0 0 0 0 0]
casa: [0 0 0 1 0 0 0 0]
coche: [0 0 0 0 1 0 0 0]
avión: [0 0 0 0 0 1 0 0]
bicicleta: [0 0 0 0 0 0 1 0]
león: [0 0 0 0 0 0 0 1]

Matriz de similitud:
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
